namespace: apps
replicaCount: 1
image:
  repository: 3a59n5l3my/backend
  pullPolicy: IfNotPresent
  tag: 1.0.0
  env:
    - name: DB_USER
      value: "dbadmin"
    - name: DB_PASSWORD
      value: "P@ssword123"
    - name: DB_HOST
      value: 
    - name: DB_DATABASE
      value: "dbinternal"
service:
  type: ClusterIP
  port: 3000
resources:
  requests:
    cpu: "0.5"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
