namespace: apps
nameOverride: "frontend"
replicaCount: 1

image:
  repository: 3a59n5l3my/frontend
  pullPolicy: IfNotPresent
  tag: 1.0.0

env:
  - name: BACKEND_PATH
    value: "backend-sertis.apps.svc.cluster.local:3000"

service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: "1"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "1Gi"
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20
  # successThreshold: 1
  httpGet:
    path: /healthz
    port: 8080


ingress:
  enabled: true
  className: "ingress-nginx"
  metadata:
    name: frontend
  hosts:
    - host:  blog.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080
